[package]
name = "jcon"
version = "0.1.0"
authors = ["Javier A. Pollak <javi.po.123@gmail.com>"]
edition = "2018"

[dependencies]
jack = "0.6"
regex = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_regex = "0.4"
